name: ms-user dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Java 24
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Gradle Check
        working-directory: ms-user
        run: gradle ckeck
      - name: Gradle build
        working-directory: ms-user
        run: gradle build
